name: dashenv
channels:
  - conda-forge
  - defaults
dependencies:
  - bcrypt=3.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - click=8.1.3
  - cryptography
  - dash=2.18
  - dill=0.3.4
  - flask=2.2.2
  - flask-compress=1.13
  - importlib-metadata=4.11
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libcxx=14.0.6
  - libffi=3.3
  - libsodium=1.0.18
  - markupsafe=2.1.1
  - ncurses=6.3
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.4
  - paramiko=2.11.0
  - pip=22.2.2
  - plotly=5.11.0
  - pycparser=2.21
  - pynacl=1.5.0
  - pyparsing=3.0.9
  - pysftp=0.2.9
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - readline=8.1.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - tenacity=8.1.0
  - tk=8.6.12
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.6
  - zipp=3.9.0
  - zlib=1.2.12
  - dash=2.18.2
  - dash-bootstrap-components=1.6.0
  - dropbox=12.0.2
